dataset: scienceqa
generation:
  temperature: 0.0
  top_p: null
  num_beams: 1
  max_new_tokens: 4
  chat_template_path: ${oc.env:EVAL_CHAT_TEMPLATE_PATH,null}
runtime:
  device: null
  batch_size: 16
  num_chunks: 1
  chunk_idx: 0
