model:
  pretrained_model_name_or_path: ${oc.env:TINYLLAVA_PRETRAINED_MODEL,output/tinyllava}
  vision_feature_layer: -2
  model_max_length: 3072
  tokenizer_use_fast: false
  attn_implementation: flash_attention_2

data:
  data_path: ${oc.env:TINYLLAVA_FINETUNE_DATA,data/finetune.json}
  image_folder: ${oc.env:TINYLLAVA_FINETUNE_IMAGE_FOLDER,data}
  dataset_adapter: llava_legacy

training:
  output_dir: output/tinyllava-custom-lora-finetune
  run_name: tinyllava-custom-lora-finetune
  precision: auto
  training_strategy: lora
  tune_type_llm: lora
  tune_type_vision_tower: frozen
  tune_type_connector: full
  per_device_train_batch_size: 8
  gradient_accumulation_steps: 4
  learning_rate: 2e-4
  num_train_epochs: 1
  save_strategy: steps
  save_steps: 500
  save_total_limit: 2
  save_only_model: false
  resume_from_checkpoint: auto
  eval_strategy: "no"
  remove_unused_columns: false
  gradient_checkpointing: true
  lr_scheduler_type: cosine
  warmup_ratio: 0.03
  logging_steps: 1
  dataloader_num_workers: 8
  report_to: tensorboard

peft:
  r: 128
  lora_alpha: 256
